apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
resources:
  - namespace.yaml
  - feature-pipeline-service.yaml
  - feature-pipeline-deployment.yaml
  - market-data-service.yaml
  - market-data-deployment.yaml
  - strategy-engine-service.yaml
  - strategy-engine-deployment.yaml
  - trade-ingress.yaml
