apiVersion: v1
kind: Service
metadata:
  name: market-data
  namespace: clab-core
  labels:
    app.kubernetes.io/name: market-data
spec:
  type: ClusterIP
  selector:
    app.kubernetes.io/name: market-data
  ports:
    - name: http
      port: 80
      targetPort: http
