apiVersion: v1
kind: Service
metadata:
  name: order-manager
  namespace: clab-core
  labels:
    app.kubernetes.io/name: order-manager
spec:
  type: ClusterIP
  selector:
    app.kubernetes.io/name: order-manager
  ports:
    - name: http
      port: 80
      targetPort: http
