apiVersion: v1
kind: Service
metadata:
  name: portfolio-engine
  namespace: clab-core
  labels:
    app.kubernetes.io/name: portfolio-engine
spec:
  type: ClusterIP
  selector:
    app.kubernetes.io/name: portfolio-engine
  ports:
    - name: http
      port: 80
      targetPort: http
