apiVersion: v1
kind: Service
metadata:
  name: projection-worker
  namespace: clab-core
  labels:
    app.kubernetes.io/name: projection-worker
spec:
  selector:
    app.kubernetes.io/name: projection-worker
  ports:
    - name: http
      port: 80
      targetPort: http
