apiVersion: v1
kind: Service
metadata:
  name: reconciliation
  namespace: clab-core
  labels:
    app.kubernetes.io/name: reconciliation
spec:
  selector:
    app.kubernetes.io/name: reconciliation
  ports:
    - name: http
      port: 80
      targetPort: http
