apiVersion: v1
kind: Service
metadata:
  name: research-labs
  namespace: clab-core
  labels:
    app.kubernetes.io/name: research-labs
spec:
  selector:
    app.kubernetes.io/name: research-labs
  ports:
    - name: http
      port: 80
      targetPort: http
