apiVersion: v1
kind: Service
metadata:
  name: strategy-engine
  namespace: clab-core
  labels:
    app.kubernetes.io/name: strategy-engine
spec:
  type: ClusterIP
  selector:
    app.kubernetes.io/name: strategy-engine
  ports:
    - name: http
      port: 80
      targetPort: http
