apiVersion: v1
kind: Service
metadata:
  name: trader-web
  namespace: clab-core
  labels:
    app.kubernetes.io/name: trader-web
spec:
  type: ClusterIP
  selector:
    app.kubernetes.io/name: trader-web
  ports:
    - name: http
      port: 80
      targetPort: http
