apiVersion: networking.k8s.io/v1
kind: Ingress
metadata:
  name: trade-ingress
  namespace: clab-core
  annotations:
    cert-manager.io/cluster-issuer: letsencrypt-prod
    nginx.ingress.kubernetes.io/backend-protocol: "HTTP"
    nginx.ingress.kubernetes.io/force-ssl-redirect: "true"
    nginx.ingress.kubernetes.io/proxy-read-timeout: "600"
    nginx.ingress.kubernetes.io/proxy-send-timeout: "600"
spec:
  ingressClassName: nginx
  tls:
    - hosts:
        - trade.clab.one
      secretName: trade-tls
  rules:
    - host: trade.clab.one
      http:
        paths:
          - path: /
            pathType: Prefix
            backend:
              service:
                name: trader-web
                port:
                  number: 80
