apiVersion: networking.k8s.io/v1
kind: Ingress
metadata:
  name: speedpoly-web-ingress
  namespace: speedpoly
  annotations:
    cert-manager.io/cluster-issuer: letsencrypt-prod
    nginx.ingress.kubernetes.io/proxy-read-timeout: "3600"
    nginx.ingress.kubernetes.io/proxy-send-timeout: "3600"
    nginx.ingress.kubernetes.io/websocket-services: speedpoly-web
spec:
  ingressClassName: nginx
  tls:
    - hosts:
        - poly.clab.one
      secretName: speedpoly-tls
  rules:
    - host: poly.clab.one
      http:
        paths:
          - path: /
            pathType: Prefix
            backend:
              service:
                name: speedpoly-web
                port:
                  name: http
