apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: vault
  namespace: argocd
spec:
  project: platform
  source:
    repoURL: https://github.com/steve-8000/k8s-stg.git
    targetRevision: main
    path: platform/vault
  destination:
    server: https://kubernetes.default.svc
    namespace: vault
  syncPolicy:
    syncOptions:
      - CreateNamespace=true
      - ServerSideApply=true
    retry:
      limit: 5
      backoff:
        duration: 10s
        factor: 2
        maxDuration: 3m
