apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization

namespace: clab-platform

resources:
  - namespace.yaml
  - configmap.yaml
  - postgres.yaml
  - services.yaml
  - dashboard.yaml
  - code-intel.yaml
