apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: openclaw-home-pvc
  namespace: claw
  labels:
    app.kubernetes.io/name: claw
spec:
  accessModes:
    - ReadWriteOnce
  storageClassName: local-path
  resources:
    requests:
      storage: 10Gi
