ingress-nginx:
  controller:
    kind: DaemonSet
    hostPort:
      enabled: true
    service:
      type: ClusterIP
    ingressClassResource:
      default: true
    config:
      use-forwarded-headers: "true"
      proxy-body-size: "50m"
      keep-alive-requests: "1000"
      upstream-keepalive-connections: "128"
      log-format-upstream: >-
        $remote_addr - $remote_user [$time_local] "$request"
        $status $body_bytes_sent "$http_referer" "$http_user_agent"
        $request_length $request_time [$proxy_upstream_name]
        [$proxy_alternative_upstream_name] $upstream_addr
        $upstream_response_length $upstream_response_time
        $upstream_status $req_id
    metrics:
      enabled: true
      serviceMonitor:
        enabled: true
        namespace: monitoring
    resources:
      requests:
        cpu: 100m
        memory: 128Mi
      limits:
        cpu: 500m
        memory: 256Mi
  defaultBackend:
    enabled: false
