apiVersion: networking.k8s.io/v1
kind: Ingress
metadata:
  name: k8s-agents-ingress
  namespace: k8s-agents
  annotations:
    cert-manager.io/cluster-issuer: letsencrypt-prod
    nginx.ingress.kubernetes.io/ssl-redirect: "true"
spec:
  ingressClassName: nginx
  tls:
    - hosts:
        - k8s.clab.one
      secretName: k8s-agents-tls
  rules:
    - host: k8s.clab.one
      http:
        paths:
          - path: /
            pathType: Prefix
            backend:
              service:
                name: k8s-agents-apiserver
                port:
                  name: http
