loki-stack:
  loki:
    enabled: true
    isDefault: false
  promtail:
    enabled: true
  grafana:
    enabled: false
    sidecar:
      datasources:
        enabled: false
  test_pod:
    enabled: false
