apiVersion: v1
kind: Secret
metadata:
  name: auth-google-secret
  namespace: clab-apps
type: Opaque
stringData:
  AUTH_SERVICE_GOOGLE_CLIENT_ID: "<REPLACE_WITH_GOOGLE_CLIENT_ID>"
  AUTH_SERVICE_GOOGLE_CLIENT_SECRET: "<REPLACE_WITH_GOOGLE_CLIENT_SECRET>"
