apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
resources:
  - namespace.yaml
  - auth-service-service.yaml
  - auth-service-deployment.yaml
  - user-service-service.yaml
  - user-service-deployment.yaml
  - ops-console-api-service.yaml
  - ops-console-api-deployment.yaml
  - notification-service-service.yaml
  - notification-service-deployment.yaml
  - control-service-service.yaml
  - control-service-deployment.yaml
