apiVersion: v1
kind: Service
metadata:
  name: ops-console-api
  namespace: clab-apps
  labels:
    app.kubernetes.io/name: ops-console-api
spec:
  selector:
    app.kubernetes.io/name: ops-console-api
  ports:
    - name: http
      port: 80
      targetPort: http
