apiVersion: networking.k8s.io/v1
kind: Ingress
metadata:
  name: polyhybrid-dashboard-ingress
  namespace: poly-rust
  annotations:
    cert-manager.io/cluster-issuer: letsencrypt-prod
    nginx.ingress.kubernetes.io/proxy-read-timeout: "3600"
    nginx.ingress.kubernetes.io/proxy-send-timeout: "3600"
    nginx.ingress.kubernetes.io/proxy-buffering: "off"
spec:
  ingressClassName: nginx
  tls:
    - hosts:
        - polyhybrid.clab.one
      secretName: polyhybrid-tls
  rules:
    - host: polyhybrid.clab.one
      http:
        paths:
          - path: /
            pathType: Prefix
            backend:
              service:
                name: polyhybrid-dashboard
                port:
                  name: http
