apiVersion: v1
kind: Service
metadata:
  name: alice-trade
  namespace: alice-trade
  labels:
    app.kubernetes.io/name: alice-trade
spec:
  type: ClusterIP
  selector:
    app.kubernetes.io/name: alice-trade
  ports:
    - name: http
      port: 80
      targetPort: http
